import 'package:flutter_test/flutter_test.dart';
import 'package:gulshantube/api/innertube_client.dart';
import 'package:gulshantube/models/video.dart';
import 'package:gulshantube/services/caption_service.dart';

/// Regression tests for the second-round audit.
///
/// Each test fails against the pre-fix implementation and names the
/// user-visible symptom it protects.
void main() {
  group('View count parsing (L-9)', () {
    test('"lac" only multiplies as a whole word', () {
      // contains() matched the substring, so any text holding "lac" — most
      // obviously "black" — was multiplied by 100,000.
      expect(InnerTubeClient.parseCount('2 lac views'), 200000);
      expect(InnerTubeClient.parseCount('5 lakh views'), 500000);

      // "black" must not be read as "lac".
      expect(InnerTubeClient.parseCount('12K black friday'), 12000);
    });

    test('still handles Indian and Western magnitudes', () {
      expect(InnerTubeClient.parseCount('1.2 crore'), 12000000);
      expect(InnerTubeClient.parseCount('3 million views'), 3000000);
      expect(InnerTubeClient.parseCount('1.5K'), 1500);
    });
  });

  group('Caption tracks from the player response (M-10)', () {
    test('reads captionTracks without scraping the watch page', () {
      final playerResponse = <String, dynamic>{
        'captions': {
          'playerCaptionsTracklistRenderer': {
            'captionTracks': [
              {
                'baseUrl': 'https://example.com/en',
                'languageCode': 'en',
                'name': {'simpleText': 'English'},
              },
              {
                'baseUrl': 'https://example.com/hi',
                'languageCode': 'hi',
                'name': {'runs': [{'text': 'Hindi (auto)'}]},
                'kind': 'asr',
              },
            ],
          },
        },
      };

      final tracks = CaptionService.parseTracks(playerResponse);

      expect(tracks.length, 2);
      expect(tracks.first.languageCode, 'en');
      expect(tracks.first.name, 'English');
      expect(tracks.first.isAutoGenerated, isFalse);
      expect(tracks.last.name, 'Hindi (auto)');
      expect(tracks.last.isAutoGenerated, isTrue);
    });

    test('tolerates a response with no captions at all', () {
      expect(CaptionService.parseTracks(<String, dynamic>{}), isEmpty);
      expect(
        CaptionService.parseTracks(<String, dynamic>{'captions': null}),
        isEmpty,
      );
      expect(
        CaptionService.parseTracks(<String, dynamic>{
          'captions': {'playerCaptionsTracklistRenderer': {}},
        }),
        isEmpty,
      );
    });

    test('skips tracks with no baseUrl', () {
      final tracks = CaptionService.parseTracks(<String, dynamic>{
        'captions': {
          'playerCaptionsTracklistRenderer': {
            'captionTracks': [
              {'languageCode': 'en', 'baseUrl': ''},
              {'languageCode': 'fr', 'baseUrl': 'https://example.com/fr'},
            ],
          },
        },
      });

      expect(tracks.length, 1);
      expect(tracks.single.languageCode, 'fr');
    });
  });

  group('Stream URL provenance (M-3)', () {
    const iosUa = 'com.google.ios.youtube/20.10.4';
    const androidUa = 'com.google.android.youtube/20.10.38';

    final details = VideoDetails(
      id: 'abc12345678',
      title: 'test',
      formats: const [
        VideoFormat(
          url: 'https://ios.example/video.mp4',
          quality: '720p',
          height: 720,
          hasVideo: true,
          hasAudio: true,
          clientUserAgent: iosUa,
        ),
        VideoFormat(
          url: 'https://android.example/video.mp4',
          quality: '360p',
          height: 360,
          hasVideo: true,
          hasAudio: true,
          clientUserAgent: androidUa,
        ),
      ],
    );

    test('returns the UA the URL was minted for', () {
      // googlevideo binds a URL to the requesting client; replaying an IOS URL
      // with an Android UA is a 403.
      expect(details.userAgentForUrl('https://ios.example/video.mp4'), iosUa);
      expect(
        details.userAgentForUrl('https://android.example/video.mp4'),
        androidUa,
      );
    });

    test('returns null for unknown or empty URLs', () {
      expect(details.userAgentForUrl('https://other.example/x.mp4'), isNull);
      expect(details.userAgentForUrl(''), isNull);
      expect(details.userAgentForUrl(null), isNull);
    });
  });

  group('Caption tracks survive stream re-resolution', () {
    test('copyWithStreams keeps the discovered tracks', () {
      const original = VideoDetails(
        id: 'abc12345678',
        title: 'test',
        captionTracks: [
          CaptionTrack(
            languageCode: 'en',
            name: 'English',
            baseUrl: 'https://example.com/en',
          ),
        ],
      );

      final updated = original.copyWithStreams(hlsUrl: 'https://x/m.m3u8');

      expect(updated.captionTracks.length, 1);
      expect(updated.captionTracks.single.languageCode, 'en');
      expect(updated.hlsUrl, 'https://x/m.m3u8');
    });
  });
}
