import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart';
import '../models/video.dart';
// Re-exported so existing importers of this service keep compiling.
export '../models/video.dart' show CaptionCue, CaptionTrack;

/// Service to fetch and parse YouTube captions/subtitles.
class CaptionService {
  // Lazily created so a call to [dispose] does not permanently break captions
  // for the rest of the process: a closed http.Client throws on every later
  // request, and the old `static final` field could never be replaced.
  static http.Client? _httpClient;
  static http.Client get _http => _httpClient ??= http.Client();

  /// Fetch available caption tracks for a video.
  /// Scrapes the watch page for caption tracks.
  ///
  /// Prefer [parseTracks] on a player response you already have: this path hits
  /// consent interstitials and bot checks (where ytInitialPlayerResponse is
  /// simply absent) and costs an extra request.
  static Future<List<CaptionTrack>> getTracks(String videoId) async {
    try {
      final uri = Uri.parse(
        'https://www.youtube.com/watch?v=$videoId',
      );
      final res = await _http.get(uri, headers: {
        'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
      }).timeout(const Duration(seconds: 10));

      if (res.statusCode != 200) return [];

      final playerResponse = extractJson(res.body, 'ytInitialPlayerResponse');
      if (playerResponse == null) {
        debugPrint(
            'CaptionService.getTracks: no ytInitialPlayerResponse for $videoId '
            '(consent wall or bot check?)');
        return [];
      }
      return parseTracks(playerResponse);
    } catch (e) {
      debugPrint('CaptionService.getTracks: $e');
      return [];
    }
  }

  /// Reads `captions.playerCaptionsTracklistRenderer` out of an InnerTube
  /// `player` response.
  static List<CaptionTrack> parseTracks(Map<String, dynamic> playerResponse) {
    final tracks = <CaptionTrack>[];
    final captions = playerResponse['captions'];
    if (captions is! Map) return tracks;

    final renderer = captions['playerCaptionsTracklistRenderer'];
    if (renderer is! Map) return tracks;

    final trackList = renderer['captionTracks'] as List? ?? const [];
    for (final track in trackList) {
      if (track is! Map) continue;
      final baseUrl = track['baseUrl']?.toString() ?? '';
      if (baseUrl.isEmpty) continue;

      final langCode = track['languageCode']?.toString() ?? '';
      final name = track['name']?['simpleText']?.toString() ??
          (track['name']?['runs'] as List?)?.map((r) => r['text']).join() ??
          langCode;
      final kind = track['kind']?.toString() ?? '';

      tracks.add(CaptionTrack(
        languageCode: langCode,
        name: name,
        baseUrl: baseUrl,
        isAutoGenerated: kind == 'asr',
      ));
    }
    return tracks;
  }

  static Future<List<CaptionCue>> getCues(String trackUrl) async {
    try {
      final uri = Uri.parse(trackUrl);
      final res = await _http.get(uri, headers: {
        'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      }).timeout(const Duration(seconds: 10));

      if (res.statusCode != 200) return [];

      return parseCaptions(res.body);
    } catch (e) {
      debugPrint('CaptionService.getCues: $e');
      return [];
    }
  }

  /// Decode XML/HTML entities found in caption text.
  ///
  /// YouTube's transcript XML is entity-encoded twice, so an apostrophe
  /// arrives as `&amp;#39;` and a literal ampersand as `&amp;amp;`. Decoding
  /// once leaves `&#39;` visible in the subtitle, so a bounded second pass
  /// runs while entities remain. The cap keeps this from unescaping
  /// indefinitely.
  static String _decodeEntities(String input) {
    var text = input;
    for (var pass = 0; pass < 2; pass++) {
      final decoded = _decodeEntitiesOnce(text);
      if (decoded == text) break;
      text = decoded;
    }
    return text;
  }

  /// Order matters: `&amp;` must be decoded last, otherwise a literal
  /// `&amp;lt;` in the transcript would wrongly become `<`.
  static String _decodeEntitiesOnce(String input) {
    var text = input
        .replaceAll('&lt;', '<')
        .replaceAll('&gt;', '>')
        .replaceAll('&quot;', '"')
        .replaceAll('&#39;', "'")
        .replaceAll('&apos;', "'")
        .replaceAll('&nbsp;', ' ');
    // Numeric entities (&#233; / &#xe9;) appear in non-English transcripts.
    text = text.replaceAllMapped(
      RegExp(r'&#(x?)([0-9a-fA-F]+);'),
      (m) {
        final code =
            int.tryParse(m.group(2)!, radix: m.group(1)!.isEmpty ? 10 : 16);
        if (code == null || code < 0 || code > 0x10FFFF) return m.group(0)!;
        return String.fromCharCode(code);
      },
    );
    return text.replaceAll('&amp;', '&');
  }

  /// Clean a raw caption body: strip markup, decode entities, collapse space.
  static String _cleanText(String raw) {
    var text = raw.replaceAll(RegExp(r'<[^>]+>'), '');
    text = _decodeEntities(text);
    // Transcript XML is pretty-printed; newlines inside a cue are not breaks.
    return text.replaceAll(RegExp(r'\s+'), ' ').trim();
  }

  /// Parse the caption formats YouTube actually serves.
  ///
  /// The timedtext endpoint returns `<transcript><text start dur>` by default
  /// and only returns TTML `<p begin end>` when `&fmt=ttml` is requested, so
  /// both are handled here. Previously only the TTML branch existed, which
  /// meant captions parsed to an empty list for effectively every video.
  @visibleForTesting
  static List<CaptionCue> parseCaptions(String xml) {
    final transcript = _parseTranscript(xml);
    if (transcript.isNotEmpty) return transcript;

    final cues = <CaptionCue>[];

    // Match <p begin="..." end="..." ...>text</p>
    final pattern = RegExp(
      r'<p\s+[^>]*?begin="([^"]*)"[^>]*?end="([^"]*)"[^>]*?>(.*?)</p>',
      dotAll: true,
    );

    for (final match in pattern.allMatches(xml)) {
      final beginStr = match.group(1) ?? '';
      final endStr = match.group(2) ?? '';
      final text = _cleanText(match.group(3) ?? '');

      if (text.isEmpty) continue;

      final start = _parseTtmlTime(beginStr);
      final end = _parseTtmlTime(endStr);

      if (start != null && end != null) {
        cues.add(CaptionCue(start: start, end: end, text: text));
      }
    }

    // Also try SRT-like format: <p begin="00:00:01.000" end="00:00:04.000">text</p>
    if (cues.isEmpty) {
      final srtPattern = RegExp(
        r'<p[^>]*?begin="(\d+:\d+:\d+[\.,]\d+)"[^>]*?end="(\d+:\d+:\d+[\.,]\d+)"[^>]*?>(.*?)</p>',
        dotAll: true,
      );
      for (final match in srtPattern.allMatches(xml)) {
        final text = _cleanText(match.group(3) ?? '');
        if (text.isEmpty) continue;

        final start = _parseSrtTime(match.group(1) ?? '');
        final end = _parseSrtTime(match.group(2) ?? '');

        if (start != null && end != null) {
          cues.add(CaptionCue(start: start, end: end, text: text));
        }
      }
    }

    // Sort by start time
    cues.sort((a, b) => a.start.compareTo(b.start));
    return cues;
  }

  /// Parse the default timedtext format:
  /// `<text start="12.34" dur="3.2">line</text>`.
  static List<CaptionCue> _parseTranscript(String xml) {
    final cues = <CaptionCue>[];
    final pattern = RegExp(
      r'<text([^>]*)>(.*?)</text>',
      dotAll: true,
      caseSensitive: false,
    );
    final startAttr = RegExp(r'\bstart="([^"]*)"');
    final durAttr = RegExp(r'\bdur="([^"]*)"');

    for (final match in pattern.allMatches(xml)) {
      final attrs = match.group(1) ?? '';
      final text = _cleanText(match.group(2) ?? '');
      if (text.isEmpty) continue;

      final start =
          double.tryParse(startAttr.firstMatch(attrs)?.group(1) ?? '');
      if (start == null) continue;
      // A missing dur (last cue on some tracks) still deserves to be shown.
      final dur =
          double.tryParse(durAttr.firstMatch(attrs)?.group(1) ?? '') ?? 4.0;

      cues.add(CaptionCue(
        start: Duration(milliseconds: (start * 1000).round()),
        end: Duration(milliseconds: ((start + dur) * 1000).round()),
        text: text,
      ));
    }

    cues.sort((a, b) => a.start.compareTo(b.start));
    return cues;
  }

  /// Parse TTML time format (e.g., "123.456s" or "00:01:23.456").
  static Duration? _parseTtmlTime(String time) {
    if (time.isEmpty) return null;

    // Format: "123.456s"
    if (time.endsWith('s')) {
      final seconds = double.tryParse(time.substring(0, time.length - 1));
      if (seconds != null) {
        return Duration(milliseconds: (seconds * 1000).round());
      }
    }

    // Format: "00:01:23.456" or "01:23.456"
    final parts = time.split(':');
    if (parts.length == 3) {
      final h = int.tryParse(parts[0]) ?? 0;
      final m = int.tryParse(parts[1]) ?? 0;
      return Duration(hours: h, minutes: m) + _parseSeconds(parts[2]);
    }
    if (parts.length == 2) {
      final m = int.tryParse(parts[0]) ?? 0;
      return Duration(minutes: m) + _parseSeconds(parts[1]);
    }

    return null;
  }

  /// Parse the seconds component, including its fraction.
  ///
  /// Reading the fraction with `int.parse` treats it as a literal millisecond
  /// count, so ".4" (400ms) became 4ms and ".45" (450ms) became 45ms — every
  /// subtitle drifted early. Parsing it as a decimal fraction keeps any digit
  /// count correct.
  static Duration _parseSeconds(String secondsPart) {
    final value = double.tryParse(secondsPart.replaceAll(',', '.')) ?? 0;
    return Duration(milliseconds: (value * 1000).round());
  }

  /// Parse SRT time format (e.g., "00:01:23,456").
  static Duration? _parseSrtTime(String time) {
    if (time.isEmpty) return null;
    final clean = time.replaceAll(',', '.');
    return _parseTtmlTime(clean);
  }

  /// Extract a JSON object from the page source by key.
  ///
  /// A non-greedy `\{.*?\}` regex cannot do this: it stops at the first `};`
  /// in the page, which almost always lands inside a nested object or inside a
  /// string value (video descriptions routinely contain `};`). That truncated
  /// text fails to decode and captions silently disappear for the video.
  /// Instead we find the opening brace and scan forward counting braces, while
  /// tracking string literals and backslash escapes so braces inside strings
  /// are ignored.
  @visibleForTesting
  static Map<String, dynamic>? extractJson(String body, String key) {
    // `var key =`, but also the bare `key =` form YouTube sometimes uses.
    final start = RegExp('(?:var\\s+)?$key\\s*=\\s*\\{').firstMatch(body);
    if (start == null) return null;

    final open = body.indexOf('{', start.start);
    if (open < 0) return null;

    var depth = 0;
    var inString = false;
    var escaped = false;

    for (var i = open; i < body.length; i++) {
      final ch = body.codeUnitAt(i);

      if (inString) {
        if (escaped) {
          escaped = false;
        } else if (ch == 0x5C) {
          escaped = true; // backslash
        } else if (ch == 0x22) {
          inString = false; // closing quote
        }
        continue;
      }

      if (ch == 0x22) {
        inString = true;
      } else if (ch == 0x7B) {
        depth++;
      } else if (ch == 0x7D) {
        depth--;
        if (depth == 0) {
          try {
            return jsonDecode(body.substring(open, i + 1))
                as Map<String, dynamic>;
          } catch (_) {
            return null;
          }
        }
      }
    }
    return null; // unbalanced / truncated page
  }

  static void dispose() {
    _httpClient?.close();
    _httpClient = null;
  }
}
